# Generated by Django 4.2.8 on 2023-12-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nascimento",
            field=models.CharField(default="", max_length=20),
        ),
    ]
