# Generated by Django 4.2.8 on 2023-12-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_cliente_nascimento"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="ativo",),
        migrations.RemoveField(model_name="cliente", name="celular",),
        migrations.RemoveField(model_name="cliente", name="rg",),
    ]
