# Generated by Django 4.2.8 on 2023-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0005_alter_cliente_aceitartermos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="aceitarTermos",
            field=models.BooleanField(default=True, max_length=3),
        ),
    ]
