# Generated by Django 4.2.8 on 2023-12-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0007_alter_cliente_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="genero",
            field=models.CharField(default="", max_length=100),
        ),
    ]
