# Generated by Django 4.2.8 on 2023-12-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        choices=[
                            ("A", "Aberto"),
                            ("PE", "Pendente de envio"),
                            ("PR", "Pendente de retorno"),
                            ("C", "Concluido"),
                        ],
                        default="A",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
